language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - openvpn

install:

  - curl icanhazip.com
#  - rm vpn.zip
  - unzip -jP $VPNPASS vpn.zip
#  - sudo openvpn --config config.ovpn --daemon
  - sudo openvpn config.ovpn &>>openvpn-client.log &
#  - sudo openvpn --config config.ovpn --daemon
#  - sudo sh vpnWait.sh
#  - sleep 10

#  - seq 10000000 > /dev/null
  - sh sleep.sh 30
  - pip install pytest coverage 
  - pip install python-coveralls
  - pip install --upgrade coverage
  - ping -c 5 8.8.8.8
  - ping -c 5 www.bbc.co.uk
  - curl icanhazip.com

#  - pip install .

#  - sudo ls -l /etc/resolv.conf
#  - sudo lsattr /etc/resolv.conf
#  - sudo chattr -i /etc/resolv.conf
#- sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf
#  - sudo ls -l /etc/resolvconf/resolv.conf.d/base
#  - sudo ls -l /etc/resolvconf/resolv.conf.d/head
#  - sudo lsattr /etc/resolvconf/resolv.conf.d/base
#  - sudo lsattr /etc/resolvconf/resolv.conf.d/head
#  - sudo echo "nameserver 8.8.8.8" >> /etc/resolvconf/resolv.conf.d/base
#  - sudo echo "nameserver 8.8.4.4" >> /etc/resolvconf/resolv.conf.d/head
#  - sudo resolvconf -u
#  - cat /etc/resolv.conf

script:
  - echo 'script'
#  - coverage --version
#  - python --version
#  - coverage run --branch -m pytest -v && coverage report -m
after_success:
  - echo 'after_success'
#  - coveralls
after_failure:
  - sleep 10

