language: python
python:
  - "3.6"
install:
  - pip install pytest coverage 
  - pip install python-coveralls
  - pip install --upgrade coverage
  - pip install .
script:
  - coverage --version
  - python --version
  - coverage run --branch -m pytest -v && coverage report -m
after_success:
  - coveralls

