language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - openvpn
install:
#  - pip install pytest coverage 
#  - pip install python-coveralls
#  - pip install --upgrade coverage
#  - pip install .
  - curl icanhazip.com
  - unzip -jP $VPNPASS vpn.zip
  - sudo openvpn --config config.ovpn --daemon
  - sudo sh vpnWait.sh
  - sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf
  - cat /etc/resolv.conf
  - ping -c 5 www.bbc.co.uk
  - ping -c 5 8.8.8.8
  - curl icanhazip.com
script:
  - coverage --version
  - python --version
  - coverage run --branch -m pytest -v && coverage report -m
after_success:
  - coveralls
