language: python
python:
  - "3.6"
addons:
  apt:
    packages:
    - openvpn
before_install:
  - unzip -P $VPNPASS vpn.zip
#  - sudo openvpn path/to/conf.ovpn &>>openvpn-client.log &
  - ping www.bbc.co.uk
  - ping 8.8.8.8
install:
  - pip install pytest coverage 
  - pip install python-coveralls
  - pip install --upgrade coverage
  - pip install .
script:
  - coverage --version
  - python --version
  - coverage run --branch -m pytest -v && coverage report -m
after_success:
  - coveralls
